### ISSUE TITLE
Re-Calculate dependent statistics on ability modifier change.

### ISSUE THREAD

**Issue by BitforceRevelator** [foundryvtt-dcc/dcc#124] opened 2021-02-06 01:48 UTC
Since ability drain / damage is quite common in DCC, I thought it could be helpful to automatically re-calculate Saving Throws, AC, HP (based on CL) & possibly even weapon statistics, when ability modifiers change due to game mechanics such as reviving a 0 HP character.

**Comment by mooped** [comment] 2021-02-06 14:46
We've been considering this for a while but it's non-trivial. We need to find a way of doing it that doesn't take away the current system which is much more immediate, works well with the Purple Sorcerer importer, and allows the player to just type their stats in straight off the sheet.

I've got some ideas for approaches to this, but it's not my top priority right now.

**Comment by mooped** [comment] 2021-03-17 22:54
We can migrate this in by adding a 'Use Base Stats' field on the weapon config. New weapons with the flag add the melee/ranged damage from the field on the sheet. Existing weapons will have the flag disabled and keep the old behaviour (which is also useful for special cases).

**Comment by mooped** [comment] 2021-05-23 18:02
Duplicate of #148 .

**Closed by mooped** 2021-05-23 18:02 UTC
Labels: enhancement
